In [30]:
# Now test bar visualization.
from bokeh.charts import Bar, output_file, show, hplot

# best support is with data in a format that is table-like
data = {
    'sample': ['1st', '2nd', '1st', '2nd', '1st', '2nd'],
    'interpreter': ['python', 'python', 'pypy', 'pypy', 'jython', 'jython'],
    'timing': [-2, 5, 12, 40, 22, 30]
}

# x-axis labels pulled from the interpreter column, stacking labels from sample column
bar = Bar(data, values='timing', label='interpreter', group='sample',
          title="Python Interpreter Sampling", legend='top_right', width=400)

# table-like data results in reconfiguration of the chart with no data manipulation
bar2 = Bar(data, values='timing', label=['interpreter', 'sample'],
           agg='mean', title="Python Interpreters", width=400)

output_file("stacked_bar.html")
show(hplot(bar, bar2))

In [3]:
corr_arr_train, mae_arr_train, mse_arr_train, r_score_arr_train, 
corr_arr_test, mae_arr_test, mse_arr_test, r_score_arr_test


data = {'source':['training', 'training', 'training', 'training', 
                  'testing', 'testing', 'testing', 'testing'], 
       'metric_name':['correlation', 'MAE', 'MSE', 'r2score', 
                      'correlation', 'MAE', 'MSE', 'r2score'], 
        'value': [np.mean(x) for x in data_summary]}

In [31]:
from bokeh.sampledata.autompg import autompg as df
from bokeh.charts import BoxPlot, output_file, show, hplot

box = BoxPlot(df, values='mpg', label='cyl', title="Auto MPG Box Plot", width=400)
box2 = BoxPlot(df, values='mpg', label='cyl', color='cyl',
                  title="MPG Box Plot by Cylinder Count", width=400)

output_file('box.html')
show(hplot(box, box2))

In [33]:
import numpy as np
import matplotlib.pyplot as plt

N = 5
menMeans = (20, 35, 30, 35, 27)
menStd = (2, 3, 4, 1, 2)

ind = np.arange(N)  # the x locations for the groups
width = 0.35       # the width of the bars

fig, ax = plt.subplots()
rects1 = ax.bar(ind, menMeans, width, color='r', yerr=menStd)

womenMeans = (25, 32, 34, 20, 25)
womenStd = (3, 5, 2, 3, 3)
rects2 = ax.bar(ind + width, womenMeans, width, color='y', yerr=womenStd)

# add some text for labels, title and axes ticks
ax.set_ylabel('Scores')
ax.set_title('Scores by group and gender')
ax.set_xticks(ind + width)
ax.set_xticklabels(('G1', 'G2', 'G3', 'G4', 'G5'))

ax.legend((rects1[0], rects2[0]), ('Men', 'Women'))


def autolabel(rects):
    # attach some text labels
    for rect in rects:
        height = rect.get_height()
        ax.text(rect.get_x() + rect.get_width()/2., 1.05*height,
                '%d' % int(height),
                ha='center', va='bottom')

autolabel(rects1)
autolabel(rects2)

plt.show()

/usr/local/lib/python2.7/dist-packages/matplotlib/collections.py:590: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if self._edgecolors == str('face'):


In [34]:
from sklearn.cross_validation import KFold
x = np.random.rand(200, 7)
y = np.random.rand(200, 1500)

In [43]:
# To test how to stack all coef_array
coeff_all = np.zeros((1500,8))
for i in range(5):
    coef_one = np.ones((1500, 8))
    coeff_all = coeff_all + coef_one

In [45]:
coeff_all = coeff_all/5

In [46]:
coeff_all

array([[ 1.,  1.,  1., ...,  1.,  1.,  1.],
       [ 1.,  1.,  1., ...,  1.,  1.,  1.],
       [ 1.,  1.,  1., ...,  1.,  1.,  1.],
       ..., 
       [ 1.,  1.,  1., ...,  1.,  1.,  1.],
       [ 1.,  1.,  1., ...,  1.,  1.,  1.],
       [ 1.,  1.,  1., ...,  1.,  1.,  1.]])

In [51]:
coeff_all[1,3]=float('NaN')

In [49]:
    isnan_index = np.nonzero(np.isnan(correlation_list_acc))
    correlation_list_acc = np.delete(correlation_list_acc, isnan_index)

In [52]:
isnan_index = np.nonzero(np.isnan(coeff_all))

In [53]:
isnan_index

(array([1]), array([3]))

In [3]:
import numpy as np
t1 = np.random.rand(3,4)
t2 = np.random.rand(10,3)
t3 = np.random.rand(11,9)

In [4]:
t4 = [t1, t2, t3]
[a1, a2, a3] = [np.nanmean(x, axis=1) for x in t4]

In [5]:
a1.shape

(3,)

In [6]:
[a1, a2, a3, a4] = [np.zeros((3,4)) for i in range(4)]

In [7]:
a1

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [16]:
a1 = np.random.rand(100, 1)
a2 = np.random.rand(100, 1)
def return_test():
    a1 = np.random.rand(100, 1)
    a2 = np.random.rand(100, 1)
    return a1.flatten(), a2.flatten()

b1, b2 = return_test()

In [17]:
b1.shape

(100,)

In [15]:
a1[:, 1] = a2.flatten()