In [27]:
import numpy as np
import json
from sklearn import preprocessing

__author__ = 'amanda'


# load the rating matrix
def prepare_rating_data():

    # Load the rating data
    rating_data = np.load('tmp/clean_rating_data.npz')
    orig_rating = rating_data['full_rating']   # 1540 * 200

    # Z-score to make everyone's ratings have zeros mean and unit std.
    scaler = preprocessing.StandardScaler().fit(orig_rating.T)  # it only fit according to the second dim. So we need to flap it first.
    dataset_mean = scaler.mean_
    dataset_std = scaler.scale_
    
    z_scored_rating = scaler.transform(orig_rating.T)
    z_scored_rating = z_scored_rating.T

    # randomly permute
    return z_scored_rating

z_scored_rating = prepare_rating_data()

In [31]:
z_scored_rating.std(axis=1).shape

(1540,)

In [35]:
a = np.random.randint(20, size=(2, 4))
print a 
print '----'
permuted_rating = a[:, np.random.permutation(a.shape[1])]
print permuted_rating

[[17  7 16  0]
 [ 6  5  0  4]]
----
[[16 17  7  0]
 [ 0  6  5  4]]


In [46]:
a = np.random.randint(10, size=(5,4))
p = a.mean(axis=0)
mean = p.mean()
std = p.std()

In [47]:
z = (p - mean)/std

In [50]:
z

array([ 0.49656353, -0.49656353,  1.32416942, -1.32416942])