In [4]:
a = ['pc'+str(i+1) for i in range(11)]

In [11]:
import pandas as pd
raw_file_path = './data/sortedImageRawList.xlsx'
df = pd.read_excel(raw_file_path, sheetname='Sheet1')
print('Loading done...\n')

Loading done...



In [16]:
import bokeh.plotting as plt
import numpy as np
import sklearn.manifold as manifold
import ujson

def load_data():
    data = np.load('tmp/pca_data.npz')
    pca_feature = data['pca_feature_arr']
    return pca_feature


def embed_show(img_list, feats, html_file='figure.html'):
    # mapper = manifold.TSNE()
    # locs = mapper.fit_transform(feats)
    print feats.shape
    locs = feats[:, 2:4]
    p = plt.figure(plot_width=2400, plot_height=1200)
    p.image_url(x=locs[:, 0], y=locs[:, 1], url=img_list, w=0.2, h=0.3, anchor="center")
    p.circle(x=locs[:, 0], y=locs[:, 1])

    plt.output_file(html_file)
    plt.save(p)
    plt.show(p) 
    
with open('data/imagePathFile.json') as data_file:
    image_list = ujson.load(data_file)
feature_list = load_data()
embed_show(image_list, feature_list)

(200, 11)


NameError: name 'load_data' is not defined

In [10]:
import numpy as np
a = np.random.rand(4,5)
a

array([[ 0.84639531,  0.03965951,  0.92775136,  0.13230804,  0.92394342],
       [ 0.73588215,  0.4428656 ,  0.9802993 ,  0.15468412,  0.00819029],
       [ 0.24398794,  0.71943551,  0.45305786,  0.00251873,  0.54072433],
       [ 0.2874137 ,  0.12017362,  0.92202205,  0.77570287,  0.75499756]])

In [11]:
a[0:2, :]

array([[ 0.84639531,  0.03965951,  0.92775136,  0.13230804,  0.92394342],
       [ 0.73588215,  0.4428656 ,  0.9802993 ,  0.15468412,  0.00819029]])

In [13]:
a[2:4,:]

array([[ 0.24398794,  0.71943551,  0.45305786,  0.00251873,  0.54072433],
       [ 0.2874137 ,  0.12017362,  0.92202205,  0.77570287,  0.75499756]])